
<table class="table">
    <thead>
        <tr class="text-center align-middle">
            <!-- <th scope="col">#</th> -->
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Adresse</th>
            <th scope="col">Complément d'adresse</th>
            <th scope="col">Ville</th>
            <th scope="col">Code postal</th>
            <th scope="col">Email</th>
            <th scope="col">Numéro</th>
         <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($customers as $customer) : ?>
            <tr class="align-middle text-center">
                <!-- <th scope="row">1</th> -->
                <td><?= $customer['lastname'] ?></td>
                <td><?= $customer['firstname'] ?></td>
                <td><?= $customer['address'] ?></td>
                <td><?= $customer['additional_address'] ?></td>
                <td><?= $customer['zip_code'] ?></td>
                <td><?= $customer['city'] ?></td>
                <td><?= $customer['email'] ?></td>
                <td><?= $customer['phone_number'] ?></td>
                <td><a href="#" type="button" class="btn btn-primary w-50">Modifier</button></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>