<!-- <link rel="stylesheet" href="/pedale-joyeuse/public/css/error.css">
<section class="notFound">
    <div class="img">
        <img src="https://assets.codepen.io/5647096/backToTheHomepage.png" alt="Back to the Homepage" />
        <img src="https://assets.codepen.io/5647096/Delorean.png" alt="El Delorean, El Doc y Marti McFly" />
    </div>
    <div class="text">
        <h1>
         <?= $errorCode ?>
        </h1>
        <h2>
            <?= $errorDescription ?>
        </h2>
        <h3>BACK TO HOME?</h3>
        <a href="/pedale-joyeuse" class="yes">YES</a>
        <a href="https://www.youtube.com/watch?v=G3AfIvJBcGo">NO</a>
    </div>
</section> -->

<main class="error-container">
    <?= $errorCode ?>
    <?= $errorDescription ?>
    <a class="error-container__link" href="/pedale-joyeuse">Retour à l'accueil</a>
</main>