<!-- Formulaire -->

<form action="/pedaleJoyeuse/Products/updateProduct/<?= $product['id'] ?>" method="POST">

  <div class="mb-3">
    <label for="productName" class="form-label">Nom du produit</label>
    <input required type="text" class="form-control" id="productName" name="productName" value="<?= $product['name'] ?>">
  </div>
  <div class="mb-3">
    <label for="productReference" class="form-label">Référence du produit</label>
    <input required type="text" class="form-control" id="productReference" name="productReference" value="<?= $product['reference'] ?>">
  </div>
  <div class="mb-3">
    <label for="productStock" class="form-label">Stock du produit</label>
    <input required type="number" class="form-control" id="productStock" name="productStock" value="<?= $product['stock'] ?>">
  </div>
  <div class="mb-3">
    <label for="productStockAlert" class="form-label">Alerte de stock</label>
    <input required type="number" class="form-control" id="productStockAlert" name="productStockAlert" value="<?= $product['stock_alert'] ?>">
  </div>
  <div class="mb-3">
    <label for="productPrice" class="form-label">Prix du produit</label>
    <input required type="number" class="form-control" id="productPrice" name="productPrice" value="<?= $product['price_ht'] ?>">
  </div>

  <div class="text-center m-5"><button type="submit" class="btn btn-primary">Valider</button></div>
</form>