<h1 class="text-center"><?= $indexTitle ?></h1>
<form method="POST" action="/pedale-joyeuse/Users/login">
  <div class="mb-3">
    <label for="username" class="form-label">Nom d'utilisateur</label>
    <input type="text" class="form-control" id="username" name="username">
  </div>
  <div class="mb-3">
    <label for="password" class="form-label">Mots de passe</label>
    <input type="password" class="form-control" id="password" name="password">
  </div>
  <div class="text-center"><button type="submit" class="btn btn-primary" name="submitLogin">Valider</button></div>
</form>