<main class="index">
  <h1 class="index__title"><?= $indexTitle ?></h1>
  <form class="index__form" method="POST" action="/pedale-joyeuse/Users/login">
    <div class="index__input">
      <input class="input" type="text" id="username" name="username">
      <label for="username">Nom d'utilisateur : </label>
    </div>
    <div class="index__input">
      <input class="input" type="password" id="password" name="password">
      <label for="password">Mots de passe : </label>
    </div>
    <div><button type="submit" class="btn" name="submitLogin">Valider</button></div>
  </form>
</main>