<p class=text-center><?= $customer['firstname'] . " " . $customer['lastname'] ?></p>

<table class="table">
        <thead>
            <tr class="align-middle">
                <th scope="col">#</th>
                <th scope="col">Date</th>
                <th scope="col">Montant</th>
                <th scope="col">Montant Total</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $i = 1;
            foreach ($invoiceData as $invoice) : ?>
                <tr class="align-middle">
                    <th scope="row"><?= $i ?></th>
                    <td><?= $invoice['creation_date'] ?></td>
                    <td><?= $invoice['amount_et'] ?>€</td>
                    <td><?= $invoice['amount_it'] ?>€</td>
                    <td class="text-end"><a href="/pedaleJoyeuse/Invoice/displayInvoice/<?= $invoice['id'] ?>" type="button" class="btn btn-primary w-100">Voir la facture</button></td>
                </tr>
            <?php 
        $i++;
        endforeach; ?>
        </tbody>
    </table>