<h1 class="text-center m-2">Outil de génération de facture</h1>

<form action="#" method="POST" class="m-5">
    <div id="invoiceContainer">
        <div class="d-flex justify-content-evenly m-2">
            <select class="form-select w-25">
                <option selected>Selectionnez un produit</option>
                <option value="1">Doussofess</option>
                <option value="2">Duracuir</option>
                <option value="3">Voiclair</option>
                <option value="4">Korn2vach</option>
                <option value="5">MacGyver</option>
            </select>
            <div class="w-50">
                <input type="number" class="form-control" placeholder="Nombre d'articles" id="numberOfProducts" name="numberOfProducts">
            </div>
        </div>
    </div>

    <div class="text-center m-5"><button type="submit" class="btn btn-primary">Valider</button></div>
</form>
<script src="/pedaleJoyeuse/public/js/invoice.js"></script>