<div class="card">
    <div class="card-body">
        <div class="container mb-5 mt-3">
            <div class="row d-flex align-items-baseline">
                <div class="col-xl-9">
                    <p style="color: #7e8d9f;font-size: 20px;">Facture >> <strong>ID: #<?= $invoiceId ?></strong></p>
                </div>
                <div class="col-xl-3 float-end">
                    <ul class="list-unstyled">
                        <li class="text-muted">Émis par : <span class="fw-bold">Pédale Joyeuse</span></li>
                        <li class="text-muted">9 rue du siège,</li>
                        <li class="text-muted">13000, Marseille</li>
                        <li class="text-muted"><i class="fa-solid fa-envelope"></i> pdj@proton.me</li>
                        <li class="text-muted"><i class="fas fa-phone"></i> 0738272849</li>
                    </ul>
                </div>
                <hr>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-xl-8">
                        <ul class="list-unstyled">
                            <li class="text-muted">Adressé à: <span style="color:#5d9fc5 ;"><?= $customerData['firstname'] . " " . $customerData['lastname'] ?></span></li>
                            <li class="text-muted"><?= $customerData['address'] . ", " . $customerData['additional_address'] ?></li>
                            <li class="text-muted"><?= $customerData['zip_code'] . " " . $customerData['city'] ?></li>
                            <li class="text-muted"><i class="fa-solid fa-envelope"></i><?= " " . $customerData['email'] ?></li>

                            <li class="text-muted"><i class="fas fa-phone"></i><?= " " . $customerData['phone_number'] ?></li>
                        </ul>
                    </div>
                    <div class="col-xl-4">
                        <ul class="list-unstyled">
                            <li class="text-muted"><i class="fas fa-circle" style="color:#84B0CA ;"></i> <span class="fw-bold">Date de création: </span><?= $customerData['creation_date'] ?></li>
                        </ul>
                    </div>
                </div>

                <div class="row my-2 mx-1 justify-content-center">
                    <table class="table table-striped table-borderless">
                        <thead style="background-color:#84B0CA ;" class="text-white">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Description</th>
                                <th scope="col">Quantité</th>
                                <th scope="col">Prix unitaire</th>
                                <th scope="col">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $i = 1;
                            foreach ($invoiceLines as $line) { ?>
                                <tr>
                                    <th scope="row"><?= $i ?></th>
                                    <td><?= $line['name'] ?></td>
                                    <td><?= $line['quantity'] ?></td>
                                    <td><?= $line['unit_price'] ?>€</td>
                                    <td><?= $line['total_price'] ?>€</td>
                                </tr>
                            <?php $i++;
                            } ?>
                        </tbody>

                    </table>
                </div>
                <div class="row">
                    <div class="col-xl-8">
                        <p class="ms-3">Notes additionnelles et informations de paiement</p>

                    </div>
                    <div class="col-xl-3">
                        <ul class="list-unstyled">
                            <li class="text-muted ms-3"><span class="text-black me-4">Sous-Total</span><?= $totalInvoice ?>€</li>
                            <li class="text-muted ms-3 mt-2"><span class="text-black me-4">TVA</span><?= $totalInvoiceVat ?>€</li>
                        </ul>
                        <p class="text-black float-start"><span class="text-black me-3"> Montant Total</span><span style="font-size: 25px;"><?= $totalWithVat ?>€</span></p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-xl-10">
                        <p>Merci pour votre achat</p>
                    </div>
                    <div class="col-xl-2">
                        <button type="button" class="btn btn-primary text-capitalize" style="background-color:#60bdf3 ;">Pay Now</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>