<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?= $pageTitle ?></title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="/pedale-joyeuse/public/sass/main.css">
  <script src="https://kit.fontawesome.com/7710422967.js" crossorigin="anonymous"></script>
</head>

<body>
  <!--  -->
  <header class="header">
    <nav class="header__navbar">
      <?php if (isset($_SESSION['id'])) { ?>
        <div id="link-container" class="header__navbar__link-container">
          <a href="/pedale-joyeuse"><span>01. </span>Accueil</a>
          <a href=" /pedale-joyeuse/Customers/displayCustomers"><span>02. </span>Fichier Client</a>
          <a href="/pedale-joyeuse/Products/stock"><span>03. </span>Stock produits</a>
          <?php if (isset($_SESSION['status']) && $_SESSION['status'] === "boss") { ?> <a href="/pedale-joyeuse/Users/salesView"><span>04. </span>Consulter les ventes</a> <?php } ?>
          <a href="/pedale-joyeuse/Users/logout"><span>End.</span> Déconnexion</a>
        </div>
        <!-- Div pour évènement menu burger -->
        <div id="menu-burger" class="header__navbar__menu-burger">
          <span class="burger-top"></span>
          <span class="burger-middle"></span>
          <span class="burger-bottom"></span>
        </div> <?php } ?>
    </nav>
  </header>
  <!--  -->

  <?= $pageContent; ?>

  <script src="/pedale-joyeuse/public/js/menu-burger.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>

</html>