<h1 class="text-center m-2">Outil de génération de facture</h1>

<form action="/pedale-joyeuse/Invoice/insertInvoice/<?= $id ?>" method="POST" class="m-5">
    <div id="invoiceContainer">

    </div>
    <div class="text-center m-5">
        <!-- Penser à typer le bouton pour qu'il ne soit pas considéré comme étant de type=submit -->
        <button id="newRow" type="button" class="btn btn-secondary m-3">Ajouter une ligne</button>
        <button type="submit" class="btn btn-primary m-3" name="submitInvoice">Valider la facture</button>
    </div>
</form>
<script src="/pedale-joyeuse/public/js/invoice.js"></script>