<h1 class="text-center">BOSS</h1>

<table class="table">
    <thead>
        <tr>
            <!-- <th scope="col">#</th> -->
            <th scope="col">Produit</th>
            <th scope="col">Référence</th>
            <th scope="col">Stock</th>
            <th scope="col">Prix</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($products as $product) : ?>
            <tr <?php if ($product['stock'] <= $product['stock_alert']) : ?> class="table-danger" <?php endif ?>>
                <!-- <th scope="row">1</th> -->
                <td><?= $product['name'] ?></td>
                <td><?= $product['reference'] ?></td>
                <td><?= $product['stock'] ?></td>
                <td><?= $product['price_ht'] ?></td>
                <td><a href="/pedaleJoyeuse/Products/formProducts/<?= $product['id'] ?>" type="button" class="btn btn-primary w-50">Modifier</button></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>